### ISSUE TITLE
The docker images seem to pull from none extant repos 

### ISSUE THREAD

**Issue by spudnic** [capitalone/ops-pipeline#2]
Maybe I am not following how to use the docker images.  Is there documentation around that part of this project, that I miss read?

brody@X401A1:~/workspace/capitalone/ops-pipeline$ cp Vagrantfiles/docker-headless/Vagrantfile .
brody@X401A1:~/workspace/capitalone/ops-pipeline$ vagrant up
Bringing machine 'opspipeline-headless' up with 'docker' provider...
==> opspipeline-headless: Creating the container...
    opspipeline-headless:   Name: ops-pipeline_opspipeline-headless_1454301088
    opspipeline-headless:  Image: tompscanlan/docker-headless-alpine:0.6
    opspipeline-headless:    Cmd: sleep 10000
    opspipeline-headless: Volume: /home/brody/workspace/capitalone/ops-pipeline:/vagrant
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "ops-pipeline_opspipeline-headless_1454301088", "-d", "-v", "/home/brody/workspace/capitalone/ops-pipeline:/vagrant", "tompscanlan/docker-headless-alpine:0.6", "sleep", "10000", {:notify=>[:stdout, :stderr]}]

Stderr: Unable to find image 'tompscanlan/docker-headless-alpine:0.6' locally
Pulling repository tompscanlan/docker-headless-alpine
time="2016-01-31T20:31:30-08:00" level=fatal msg="Error: image tompscanlan/docker-headless-alpine:0.6 not found" 

Stdout: 
brody@X401A1:~/workspace/capitalone/ops-pipeline$ docker pull tompscanlan/docker-headless-alpine
Pulling repository tompscanlan/docker-headless-alpine
FATA[0001] Error: image tompscanlan/docker-headless-alpine:latest not found 
brody@X401A1:~/workspace/capitalone/ops-pipeline$

**Comment by gasserk** [comment]
Currently the code for the pipeline is public, but the produced images (virtualbox and vmware_desktop VMs) are private to the opspipeline Atlas registry, while the Docker containers are private to the opspipeline Docker Hub org.  You may run the pipeline and target your own accounts at these or other registries, and consume the results as you've attempted above.  The project team has not yet decided to publish the resulting binary artifacts, but you are welcome to do so as meets your needs.

**Comment by spudnic** [comment]
Ok, thanks for the clarification.
